### ISSUE TITLE
Supporting AsyncImage

### ISSUE THREAD

**Issue by konrain** [Iaenhaall/AttributedText#3]
Hi there, thanks for the library

Would it be possiable to somehow support img tags to render the image in the src itself? using something like AsyncImage(url: srcFromImage)

```swift 
 private let tags: Dictionary<String, (Text) -> (Text)> = [
   "img": { _ in Text("\(Image("\(srcTagInaccessible)"))") }
]
```

Thanks again.

**Comment by iaenhaall** [comment]
My solution only displays formatted text and does so with some limitations.

If you need to display more complex HTML code, try `UIWebView` for example. But please note that this solution doesn't work quickly.

In the future, I plan to significantly expand the capabilities of my solution. But image support is **not** part of my plans.

**Comment by konrain** [comment]
Do you think it might be difficult to add it by converting the return type from Text to View and doing some prechecks for img tag? I can make a PR, just don't know which approach to take or if its a direction you want to go with the library.

**Comment by iaenhaall** [comment]
In the future I plan to add support for attributes and HTML-encoded characters (e.g. `&amp;`).

To display additional elements (e.g. images), it is probably better to use `ZStack`. I think the main problem will be how you define the type of elements inside the stack. I'm not sure that this is a simple task. Especially if you plan to support something other than images.
